name: Build

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 23 * * *"

env:
  FABRIC_VERSION: 2.2
  SOFTHSM2_CONF: ${{ github.workspace }}/test/ts-fixtures/hsm/softhsm2.conf

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SoftHSM
        run: |
          sudo apt-get install softhsm2
          softhsm2-util --init-token --slot 0 --label "ForFabric" --pin 98765432 --so-pin 1234

      - name: npm install
        run: npm install

      - name: Generate credentials
        run: npm run installAndGenerateCerts

      - name: Pull Fabric images
        run: npm run pullFabricImages

      - name: Run tests
        run: npm test
