name: "Security vulnerability scan"

on:
  schedule:
    - cron: "20 0 * * *"

jobs:
  npm-audit:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        package:
          - fabric-ca-client
          - fabric-common
          - fabric-network
          - fabric-protos
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Scan
        run: |
          npm install --package-lock-only
          npm audit --omit=dev
        working-directory: ${{ matrix.package }}
